### ISSUE TITLE
wish: please add "Browser Support" section to the README

### ISSUE THREAD

**Issue by markstos** [bbatliner/vex2#1]
The original Vex included a "Browser Support" section which documented the browsers it was known to work on. Publishing similar docs would be helpful here as well.

**Comment by bbatliner** [comment]
Agreed. When I was rewriting vex without jQuery, my thinking was to drop IE8 support (some ES5 features that are helpful for writing vanilla JavaScript aren't present in IE8) but to keep support for all of the other browsers listed in the original vex list.

 I can test on Opera, Firefox, Chrome, and Chrome for Android, myself. I opened #4 because it seems like I lost Firefox compatibility with the rewrite.

Just wondering, are you on a Mac or iPhone to be able to test on Safari and iOS Safari? Would be nice to have that verification.

**Comment by markstos** [comment]
I've in favor of dropping IE 8 support. People can still use vex-1 if they want that.  According to this, IE 8 is about drop below the 5% usage threshold: http://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0   

That's a threshold that many places have used for determining browser support, based on their own sites usage once they have enough data.

I don't have access to a Mac or iPhone now but can have my Mac team members check next week.  My family runs Ubuntu and Android at home.

**Comment by bbatliner** [comment]
I ran some tests tonight with browserling (I hit my free session limit >.>) on IE9 and identified some issues that would prevent vex2 from working in older browsers. Now included is a polyfill for `classList` and some revisions to the code that should let it work in all of the browsers I added to the README.

**Comment by markstos** [comment]
Great, thanks!
